[project]
name = "vascularcircuit0d"
version = "0.1.0"
description = "Lightweight python project for post-processing 0D vascular circuit simulations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["matplotlib>=3.10.7", "numpy>=2.3.5"]
